#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
# Import('env')
Import('nigrelli_env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
def local_build():
    local_env = nigrelli_env.Clone();

    rootlibs  = local_env['ROOTLIBS']
    if ( not ("EG"   in rootlibs)): rootlibs.insert(rootlibs.index("Physics")+1,"EG"  );
    if ( not ("Eve"  in rootlibs)): rootlibs.insert(rootlibs.index("EG"     )+1,"Eve" );
    if ( not ("Geom" in rootlibs)): rootlibs.insert(rootlibs.index("Eve"    )+1,"Geom");
    if ( not ("RGL"  in rootlibs)): rootlibs.insert(rootlibs.index("Geom"   )+1,"RGL" );

    debug            = False
    stn_helper       = stntuple_helper(local_env,debug);

    skip_list        = []
    dict_skip_list   = []
    list_of_cc_files =  local_env.Glob('*.cc', strings=True);

    stntuple_libs    = ['Stntuple_alg', 'Stntuple_obj' , 'Stntuple_loop',
                        'Stntuple_gui', 'Stntuple_geom', 'Stntuple_base'];

    if (os.getenv("STNTUPLE_MC_GEN") == None): 
        dict_skip_list.append("TPhotosAnaModule_linkdef.h");
        skip_list.append("TPhotosAnaModule.cc");
    else:
        stntuple_libs.append("mc_photos");

    stn_helper.handle_dictionaries(".hh",dict_skip_list);

    libs             = stntuple_libs + rootlibs + [];
    stn_helper.build_libs(list_of_cc_files, skip_list, libs);

    rootlibs.remove("RGL" );
    rootlibs.remove("Eve" );
    rootlibs.remove("EG"  );
    rootlibs.remove("Geom");
#------------------------------------------------------------------------------
local_build()
# print "tmpdir:"+env['TMP_LIB_DIR']
